services:
    Daric\SilasJoisten\Sonata\MultiUploadBundle\Pool\ProviderChain: ~

    Daric\SilasJoisten\Sonata\MultiUploadBundle\Twig\MultiUploadExtension:
        arguments: [ '@Daric\SilasJoisten\Sonata\MultiUploadBundle\Pool\ProviderChain' ]
        tags: [ 'twig.extension' ]
